#!/usr/bin/env node
/**
 * Bonus 4 — Lightweight multi-step Gemini workflow:
 *   1) Summarize Bubble export shape
 *   2) Draft Postgres DDL notes for TCL customer schema
 *   3) Suggest RLS policies for customers vs staff
 *
 * Usage:
 *   node scripts/migration-agent.mjs
 *
 * Requires GOOGLE_API_KEY in .env.local
 * Writes: scripts/agent-pipeline-output.md
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '..', '.env.local') });
dotenv.config({ path: join(__dirname, '..', '.env') });

const key = process.env.GOOGLE_API_KEY?.trim();
if (!key) {
  console.error('Set GOOGLE_API_KEY in .env.local');
  process.exit(1);
}

const model = new GoogleGenerativeAI(key).getGenerativeModel({
  model: 'gemini-2.0-flash',
  generationConfig: { temperature: 0.3, maxOutputTokens: 2048 },
});

async function step(name, prompt) {
  console.log(`\n→ ${name}…`);
  const result = await model.generateContent(prompt);
  const text = result.response.text().trim();
  console.log(text.slice(0, 200) + (text.length > 200 ? '…' : ''));
  return text;
}

const sampleJson = readFileSync(join(__dirname, 'bubble-sample-export.json'), 'utf8');

const analysis = await step(
  'Agent 1 — Schema analysis',
  `You are a data migration analyst. Study this sample Bubble JSON export (10 rows, mixed types).
List: entity types, field naming patterns, option-set style fields, nullable patterns, and risks for mapping to PostgreSQL.
Be concise (bullet points, max 400 words).

JSON:
${sampleJson.slice(0, 12000)}`,
);

const sqlDraft = await step(
  'Agent 2 — SQL generation',
  `Based on this analysis of a Bubble app for custom apparel orders, propose:
- Postgres enums (user types, order status, print types, proof status)
- Core tables: users (linked to auth), products, orders, proofs, revision_requests
- Key columns and FKs
Output as structured markdown with SQL snippets (CREATE TYPE / CREATE TABLE style). Do not exceed 800 words.

Analysis from previous step:
${analysis}`,
);

const rls = await step(
  'Agent 3 — RLS suggestions',
  `Given this planned schema context, suggest Row Level Security policies for:
- Customers: only their orders, proofs on those orders, their revision requests, read catalog products
- Staff (account_manager): full read on operational tables
Keep policy names readable. Markdown bullet list + example CREATE POLICY statements.

Schema draft summary:
${sqlDraft.slice(0, 4000)}`,
);

const out = `# Migration agent pipeline output (Gemini)

_Generated by \`scripts/migration-agent.mjs\` — Bonus 4 demo._

## Step 1 — Bubble / schema analysis

${analysis}

---

## Step 2 — SQL draft

${sqlDraft}

---

## Step 3 — RLS suggestions

${rls}
`;

const outPath = join(__dirname, 'agent-pipeline-output.md');
writeFileSync(outPath, out, 'utf8');
console.log(`\nWrote ${outPath}`);
